version: '3'

services:
  redis:
    container_name: "redis-service"
    hostname: redis
    image: "redis:latest"
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass mypassword
    ports:
      - '6379:6379'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
